version: "3"
services:
  app:
    build:
      context: .
    depends_on:
      - postgres
      - mongo
    environment:
      DATABASE_URL: postgres://root:rootPassword@postgres:5432/postgres-db
      NODE_ENV: development
      PORT: 5000
    ports:
      - "5000:5000"
    restart: always
  postgres:
    container_name: postgres
    image: postgres:12
    ports:
      - "5436:5432"
    restart: always
    volumes:
      - ./postgres-initdb.sh:/docker-entrypoint-initdb.d/init.sh
      - postgresdata:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: root
      POSTGRES_PASSWORD: rootPassword
      POSTGRES_DB: postgres-db
  mongo:
    container_name: mongo
    image: mongo
    ports:
      - "27017:27017"
    volumes:
      - data-volume:/data/db
volumes:
  data-volume:
  postgresdata:
