export enum USER {
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED',
  SET_USER_ITEM = 'SET_USER_ITEM',
}

export enum GAME_ACTIONS {
  PAUSE = 'PAUSE',
  RESUME = 'RESUME',
  FINISH = 'FINISH',
}
