export enum USER {
  SET_FAILED_STATUS = 'SET_FAILED_STATUS',
  SET_SUCCESS_STATUS = 'SET_SUCCESS_STATUS',
  SET_USER_INFO = 'SET_USER_INFO',
  LOGOUT = 'LOGOUT',
  SET_POINT = 'SET_POINT',
  SET_THEME = 'SET_THEME',
}
